# Generated by Django 2.2.6 on 2020-03-13 22:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_drinks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('F', 'Drinks for the first person'), ('S', 'Drinks for the second person'), ('N', 'No drink for either')], default='N', max_length=1)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('first_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_person', to=settings.AUTH_USER_MODEL)),
                ('second_person', models.ForeignKey(help_text='Please select the user you want to add in your list', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_person', to=settings.AUTH_USER_MODEL, verbose_name='User to add')),
            ],
        ),
    ]
