# Generated by Django 2.2.6 on 2020-03-14 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payyourdrink', '0002_auto_20200313_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_first_player', models.BooleanField(default=True)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payyourdrink.Deal')),
            ],
        ),
    ]
