# Generated by Django 2.2.6 on 2020-03-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payyourdrink', '0004_drink_by_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='for_first_player',
            new_name='for_first_person',
        ),
        migrations.AlterField(
            model_name='drink',
            name='deal',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='payyourdrink.Deal'),
        ),
    ]
