# Generated by Django 2.2.6 on 2020-03-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payyourdrink', '0005_auto_20200314_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='number_of_drinks',
        ),
    ]
