# Generated by Django 2.2.6 on 2020-03-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payyourdrink', '0006_remove_deal_number_of_drinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='status',
        ),
    ]
