# Generated by Django 2.2.6 on 2020-03-26 16:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(default='cell.png', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('y', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castlemaze.Card')),
                ('displayed_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_displayed_card', to='castlemaze.Card')),
                ('game', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='castlemaze.Game')),
            ],
        ),
    ]
