# Generated by Django 2.2.6 on 2020-03-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0002_card_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_cards', models.IntegerField(default=10)),
                ('cards', models.ManyToManyField(to='castlemaze.Card')),
            ],
        ),
    ]
