# Generated by Django 2.2.6 on 2020-03-26 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0003_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='card_orientation',
            field=models.CharField(choices=[('N', 'NORD'), ('E', 'EAST'), ('S', 'SOUTH'), ('W', 'West')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='deck',
            name='current_card_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='castlemaze.Deck'),
        ),
    ]
