# Generated by Django 2.2.6 on 2020-03-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0007_auto_20200327_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='number_of_cards',
        ),
    ]
