# Generated by Django 2.2.6 on 2020-03-28 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0008_remove_deck_number_of_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='Game', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cell',
            name='x',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)]),
        ),
        migrations.AlterField(
            model_name='cell',
            name='y',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
