# Generated by Django 2.2.6 on 2020-03-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0009_auto_20200328_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_number_of_players',
            field=models.IntegerField(default=6),
        ),
    ]
