# Generated by Django 2.2.6 on 2020-03-30 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0011_cell_cell_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='card_selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='castlemaze.Card'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_type',
            field=models.CharField(default='maze', max_length=100),
        ),
    ]
