# Generated by Django 2.2.6 on 2020-03-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0012_auto_20200330_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='clickable',
        ),
    ]
