# Generated by Django 2.2.6 on 2020-03-30 20:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0013_remove_cell_clickable'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='castlemaze.Cell'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='y',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
