# Generated by Django 2.2.6 on 2020-03-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0014_auto_20200330_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_tile',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('P', 'Preparation'), ('S', 'Started'), ('E', 'Ended')], default='P', max_length=1),
        ),
    ]
