# Generated by Django 2.2.6 on 2020-03-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0015_auto_20200331_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
        migrations.AddField(
            model_name='deck',
            name='card_order',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
