# Generated by Django 3.0.5 on 2020-04-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0019_auto_20200402_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=0),
        ),
    ]
