# Generated by Django 3.0.5 on 2020-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0020_player_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='blue_team',
            field=models.ManyToManyField(related_name='blue_team', to='castlemaze.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='red_team',
            field=models.ManyToManyField(related_name='red_team', to='castlemaze.Player'),
        ),
    ]
