# Generated by Django 3.0.5 on 2020-04-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0021_auto_20200403_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='cell',
            new_name='pawn_cell',
        ),
        migrations.RemoveField(
            model_name='game',
            name='blue_team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='red_team',
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='castlemaze.Game'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(default='red', max_length=50),
            preserve_default=False,
        ),
    ]
