# Generated by Django 3.0.5 on 2020-04-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0023_auto_20200405_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number_of_round_left',
            field=models.IntegerField(default=20),
        ),
    ]
