# Generated by Django 3.0.5 on 2020-04-06 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0023_auto_20200405_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='deck',
        ),
        migrations.AddField(
            model_name='deck',
            name='deck_type',
            field=models.CharField(default='tile', max_length=100),
        ),
        migrations.AddField(
            model_name='deck',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='castlemaze.Game'),
        ),
    ]
