# Generated by Django 3.0.5 on 2020-04-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0024_auto_20200406_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='cards',
        ),
        migrations.AddField(
            model_name='player',
            name='action_cards',
            field=models.ManyToManyField(related_name='action_cards', to='castlemaze.Card'),
        ),
        migrations.AddField(
            model_name='player',
            name='status_played_tile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='status_player_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='tile_cards',
            field=models.ManyToManyField(related_name='tile_cards', to='castlemaze.Card'),
        ),
    ]
