# Generated by Django 3.0.5 on 2020-04-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0025_auto_20200407_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='status_player_action',
            new_name='status_played_action',
        ),
    ]
