# Generated by Django 3.0.5 on 2020-04-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0026_auto_20200407_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='remaining_moves',
            field=models.IntegerField(default=0),
        ),
    ]
