# Generated by Django 3.0.5 on 2020-04-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0027_player_remaining_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='trap',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='trap_visible',
            field=models.ManyToManyField(related_name='trap_cards', to='castlemaze.Card'),
        ),
    ]
