# Generated by Django 3.0.5 on 2020-04-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0028_auto_20200408_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='activated_open_bottom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='activated_open_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='activated_open_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='activated_open_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='activated_traps',
            field=models.ManyToManyField(related_name='activated_traps', to='castlemaze.Card'),
        ),
    ]
