# Generated by Django 3.0.5 on 2020-04-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('castlemaze', '0030_game_team_turn'),
        ('castlemaze', '0024_game_number_of_round_left'),
    ]

    operations = [
    ]
