# Generated by Django 2.2.6 on 2020-03-15 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepinmind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
