# Generated by Django 2.2.6 on 2020-03-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0002_game_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='Game',
            new_name='game',
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First player to move'), ('S', 'Second player to move'), ('W', 'First player wins'), ('L', 'Second player wins'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
